### ISSUE TITLE
Lỗi hiển thị ngày nếu dài ngày

### ISSUE THREAD

**Issue by mitchdoan** [InkWhale-net/frontend#10]
![image](https://github.com/InkWhale-net/frontend/assets/117429099/e132d0b8-cdc1-48cd-820f-fc113f517806)

should display like this
![image](https://github.com/InkWhale-net/frontend/assets/117429099/479ecfbf-12a2-4adf-a54d-9489a476fc1b)

**Comment by phoebehoang85** [comment]
ok. close case
