### ISSUE TITLE
Hiển thị status thông báo pool token/nft full slots

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#118]
Thông báo ngoài pool là pool đã đầy slots hoặc số slot còn lại được stake ở pool cho user dễ hiểu. Hoặc có thể disable button stake nếu full slot
![image](https://github.com/InkWhale-net/frontend/assets/55371727/9300a8ff-e1fd-4884-9ae6-724ee6aec918)

**Comment by nad128668** [comment]
<img width="595" alt="Screenshot 2023-06-16 at 16 13 33" src="https://github.com/InkWhale-net/frontend/assets/88643486/2c97cbfd-22d2-4747-8af6-7df728109c56">
