### ISSUE TITLE
Tinh chỉnh lại table NFT pools

### ISSUE THREAD

**Issue by nad128668** [InkWhale-net/frontend#119]
<img width="1241" alt="Screenshot 2023-06-15 at 09 38 40" src="https://github.com/InkWhale-net/frontend/assets/88643486/6d6f9852-82ec-41c2-9810-d08996a7e05e">
Đoạn này bị gần sát nhau quá nên nhìn ko đẹp, dãn co các phần khác của table để hiện đẹp hơn. Cột Multiplier?

**Comment by hiro2kqt** [comment]
bảng này đang bị thiếu width
![image](https://github.com/InkWhale-net/frontend/assets/76714933/68a969a6-67fa-4711-8c6f-fd1d3a5e3c46)
cột my stake cuối bị khuất mất, hiện đang để maxW là 1440 có thể tăng lên 1600 hay bỏ bớt 1 cột để có không gian hiển thị @nad128668
