### ISSUE TITLE
Date is not intelligent yet

### ISSUE THREAD

**Issue by mitchdoan** [InkWhale-net/frontend#13]
Start day phải chọn ở hiện tại or tương lai or có thể được chọn ở quá khứ nhưng pool k được kết thúc trong quá khứ luôn

![image](https://github.com/InkWhale-net/frontend/assets/117429099/1eb4c9a4-0f9d-4b57-8c70-843dc1dc1308)

**Comment by nad128668** [comment]
chỉ start ở hiện tại và tương lai, ko cho start ở quá khứ

**Comment by hiro2kqt** [comment]
@nad128668
