### ISSUE TITLE
Lỗi hiển thị lúc chọn ngày bắt đầu trong tương lai

### ISSUE THREAD

**Issue by mitchdoan** [InkWhale-net/frontend#14]
Cũng có bug này nữa  anh nha, em chọn ngày bắt đầu trong tương lai
Bug 1: Lẽ ra phải disable cái pool đó đi và user k thể vào stake khi chưa bắt đầu
Bug 2: Hiển thị status là coming soon or start at.... chứ k phải đếm ngày kết thúc như cái pool đang live được

![image](https://github.com/InkWhale-net/frontend/assets/117429099/9a34d046-3511-4756-b351-fb9c0b07629e)

![image](https://github.com/InkWhale-net/frontend/assets/117429099/b93f26fe-36ad-491f-8df7-86acb693f082)

2 cái em khoanh nớ là chọn thời gian bắt đầu ở tương lai á anh nha

Khi em vào pool thì nó vẫn cho stake được, nhưng khi approval transaction thì mới báo lỗi

**Comment by phoebehoang85** [comment]
re-test ok. close case.

![image](https://github.com/InkWhale-net/frontend/assets/107900832/19e4371c-03e5-4bf0-a7b2-f2ae975d9f6b)
