### ISSUE TITLE
Lỗi hiện thị lúc burn token

### ISSUE THREAD

**Issue by mitchdoan** [InkWhale-net/frontend#15]
Bug hiển thị lỗi sai. Em burn token nhưng nhập số có chữ e thì hiển thị vậy k đúng. Phải nói là invalid among chứ a nhỉ, với lại to burn chứ khum phải to transfer

![image](https://github.com/InkWhale-net/frontend/assets/117429099/41de57de-1990-4961-89a7-ba6244d4e7c0)

**Comment by thienvip107** [comment]
e là một kiểu số nên lib nó ko nhận ạ, em đang validate bỏ kí tự thôi ạ

**Comment by phoebehoang85** [comment]
re-test ok. close case
