### ISSUE TITLE
Launchpad: project kí hoàn thành nhưng chờ 5-10 phút sau mới lên

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#219]
project kí hoàn thành nhưng mãi 5-10 phút sau mới lên

tên project pizza

![image](https://github.com/InkWhale-net/frontend/assets/107900832/202a2d6c-7859-43d8-aee2-e3b4f4fff75d)

**Comment by hiro2kqt** [comment]
ref https://github.com/InkWhale-net/frontend/issues/228

**Comment by phoebehoang85** [comment]
ok close case
