### ISSUE TITLE
Launchpad: nhiều project tạo xong không hiện lên

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#228]
Check các project đã tạo nhưng k thấy lên (đã thấy trừ phí & báo tạo thành công)
- Pizza 1
- Pizza 2
- IPPA
- IPPB

**Comment by hiro2kqt** [comment]
sau khi tạo thì project sẽ chưa vào trạng thái active, sẽ cần contract owner(ví albert active ở /admin) thì mới hiện lên ở /launchpad và có thể thực hiện mua bán, project pizza trước đó e đã active

**Comment by phoebehoang85** [comment]
close case
