### ISSUE TITLE
Launchpad: tính giá bán + trade fee nhầm

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#245]
Giá bán: 0.1
số lượng mua: 10000
Giá phải trả: 1000 (trừ của buyer)
Phía trade 5%: 50 (về ví sàn)
Owner được nhận: 950

hiện tại: người mua phải trả 1050

![image](https://github.com/InkWhale-net/frontend/assets/107900832/4db0f038-7ba4-4e4b-ab54-f25a18dc158c)

**Comment by hiro2kqt** [comment]
#248
user nhập token amount -> tính fee -> sau mua user nhận được đúng số amount đã nhập
user nhập az amount -> tính fee amount user nhập = cost + fee 5% -> sau mua user nhập được số token đúng với lượng az đã nhập
