### ISSUE TITLE
cần validate phase cap

### ISSUE THREAD

**Issue by vup2p** [InkWhale-net/frontend#305]
![image](https://github.com/InkWhale-net/frontend/assets/102939807/46aaa355-9c72-4b12-a7c2-780b716b46db)

**Comment by vup2p** [comment]
cần hiển thị phase cap 
![image](https://github.com/InkWhale-net/frontend/assets/102939807/1f7a2c9f-9643-4bec-8341-1697b5d40bc4)

**Comment by langdon0003** [comment]
update @vup2p 
![image](https://github.com/InkWhale-net/frontend/assets/35419213/c3b64b92-0fbe-4b72-acd1-ef3357902930)
