### ISSUE TITLE
Transfer với giá trị bằng 0 token nhưng vẫn approval trên Subwallet

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#31]
**TH1:** Balance: 0
- Transfer: 0
- Result: Vẫn approval trên ví --> sau chạy xong mới báo lỗi
**TH2:** Balance >0
- Transfer: 0 
- Result: Vẫn chạy bình thường (không báo lỗi, phần này mình nghĩ nên có message thông báo lỗi bạn nên transfer ít nhất >0 or ít nhất 1 gì đó)
![image](https://github.com/InkWhale-net/frontend/assets/55371727/47e060bf-2daf-4606-acf8-6b0350d185e7)

**Comment by phoebehoang85** [comment]
re-test & close case

![image](https://github.com/InkWhale-net/frontend/assets/107900832/a6c9b9bb-6825-4db7-ba9d-66efed16ae79)
