### ISSUE TITLE
KYC: hiển thị lặp 2 lần cho 1 địa chỉ

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#311]
hiển thị lặp 2 lần cho 1 địa chỉ

![image](https://github.com/InkWhale-net/frontend/assets/107900832/df4bc952-d5a4-41d3-a47c-2af47adf9c25)

**Comment by langdon0003** [comment]
E ko tái hiện lỗi được.
chị follow thử xem còn bị không nhé @phoebehoang85
