### ISSUE TITLE
KYC: những address đã import rồi thì bỏ ô tick ghi note imported

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#312]
những address đã import rồi thì bỏ ô tick ghi note imported và không cho chỉnh sửa nữa

2 address ở trên 1 dòng đã import, 1 dòng not approved, nhưng vẫn sửa được giá, số lượng, vẫn có ô tick (mặc dù không tick được). Nên bỏ ô tick, thay bằng imported hoặc not approved, không cho sửa.

Chỉ những address chưa được import và đã được approved thì mới có ô tick và cho sửa.

![image](https://github.com/InkWhale-net/frontend/assets/107900832/a10fd6ed-f4a0-42c4-bee4-e8991758813d)

**Comment by langdon0003** [comment]
updated 
@phoebehoang85
