### ISSUE TITLE
KYC: nếu không connect ví và xác định địa chỉ ví đúng thì ẩn Click here to KYC đi

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#313]
nếu không connect ví và xác định địa chỉ ví đúng thì ẩn Click here to KYC đi

user không biết nên cứ kyc xong thì chờ nhưng thực tế không biết là mình chưa được ghi nhận địa chỉ ví

![image](https://github.com/InkWhale-net/frontend/assets/107900832/f5918019-e2f9-4065-bafd-dbd3fa691638)

Ấn nút Click here to KYC
![image](https://github.com/InkWhale-net/frontend/assets/107900832/d5028215-d55b-4d6a-b634-e804827e34b5)

**Comment by langdon0003** [comment]
updated
@phoebehoang85
