### ISSUE TITLE
KYC: có thể sửa thông tin khi đã KYC không?

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#314]
nếu đã undefined mà KYC xong, sau đó connect ví và KYC lại, thì kết quả vẫn là undefined và không được ghi nhận địa chỉ ví, 

với các trường hợp vì 1 lý do nào đấy mà KYC xong bị undefined, sau đó quay lại KYC lại hệ thống blockpass sẽ báo m đã KYC thành công, nhưng users muốn đổi địa chỉ ví hoặc khi đã undefined mà muốn thay địa chỉ ví, users thường liên hệ với creator để sửa thông tin

Vậy creator có sửa được không? Hình như trong trang này không sửa được?

![image](https://github.com/InkWhale-net/frontend/assets/107900832/55249017-9361-4ab0-a265-986898f4c867)

**Comment by langdon0003** [comment]
Chị thử vào chỗ này trong Blockpass đổi address thử.

[Screencast from 11-09-2023 08:05:29 AM.webm](https://github.com/InkWhale-net/frontend/assets/35419213/3ee85562-54b0-4995-b8b7-c6e44d086166)

**Comment by langdon0003** [comment]
@phoebehoang85
