### ISSUE TITLE
Sửa / add text

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#315]
Phase cap: (chỗ dấu ?): Total amount of tokens to be sold in this phase.

![image](https://github.com/InkWhale-net/frontend/assets/107900832/26e4402b-f7ca-48d2-806d-7da0e234aadf)

**Comment by phoebehoang85** [comment]
@langdon0003 
Check lại toast chỗ Phase Edit, ở đây báo Enter Phase Time Range

Check lại toast cho các trường hợp: overlap time, phase time sai, phase cap exceed available token amount, ...

![image](https://github.com/InkWhale-net/frontend/assehình như cứ lỗi là toast check Enter Phase Time Rangets/107900832/f26fb923-b629-42bf-ad0c-48f308d002b8)

**Comment by phoebehoang85** [comment]
Create project >> Add phase: Thêm dấu chấm hỏi ở cuối ở Vesting release period

![image](https://github.com/InkWhale-net/frontend/assets/107900832/ad9f360d-c194-4669-aece-b90ac5bb72bb)

**Comment by phoebehoang85** [comment]
Bỏ text setup whitelist nếu create project with KYC ở 3 bước kí khi tạo 

![image](https://github.com/InkWhale-net/frontend/assets/107900832/07f582ab-f06f-4eaf-9438-fa8458d0f21e)

**Comment by phoebehoang85** [comment]
Sửa text chỗ Click here to KYC thành "This project requires all users to KYC in order to buy. Click here to KYC."

![image](https://github.com/InkWhale-net/frontend/assets/107900832/714d571d-48eb-4097-85a7-b60e0e44ba2c)

**Comment by phoebehoang85** [comment]
Sửa text chỗ đường dẫn: All launchpads thành "All launchpad projects"

![image](https://github.com/InkWhale-net/frontend/assets/107900832/ed2062e5-1842-48d4-abb0-c40aa545fa24)

**Comment by phoebehoang85** [comment]
Total token for sale
Start Time
End Time
(bỏ presale đi)

![image](https://github.com/InkWhale-net/frontend/assets/107900832/d7c41cc6-9fac-476a-b7ac-e8621c893464)

**Comment by phoebehoang85** [comment]
Update phases --> Manage phases
Available token amount --> Balance (cho lên bên trái phía trên)

Nút Create new phase cho xuống dưới cùng bên trái


![image](https://github.com/InkWhale-net/frontend/assets/107900832/bfd6aa6a-e391-43fe-b2f1-3f8b5baa6d4b)

![telegram-cloud-photo-size-5-6228649091664033250-y](https://github.com/InkWhale-net/frontend/assets/107900832/a4aba051-d3c0-459b-b710-e991a2dc089f)

**Comment by phoebehoang85** [comment]
Khi đã Update phases, chọn phase xong:
Update phases --> Manage xyz Phase
Available token amount --> Balance (cho lên bên trái phía trên)

![image](https://github.com/InkWhale-net/frontend/assets/107900832/3da2fd8b-6414-4419-8dae-3b2cd7be128c)

![telegram-cloud-photo-size-5-6228649091664033252-y](https://github.com/InkWhale-net/frontend/assets/107900832/93274b2f-3cc9-47f1-9fb7-69ada2a29bd7)

Phase Cap tooltip: Total token for sale in this phase
![telegram-cloud-photo-size-5-6228649091664033251-x](https://github.com/InkWhale-net/frontend/assets/107900832/6e98e1c7-486d-4a5e-84d0-0ddddef9a550)

**Comment by phoebehoang85** [comment]
KYC Manager --> Manage KYC & Whitelist

![telegram-cloud-photo-size-5-6228649091664033253-x](https://github.com/InkWhale-net/frontend/assets/107900832/afb942e6-7296-4ab0-accb-779685ff56fb)

**Comment by phoebehoang85** [comment]
Update KYC Whitelist --> Manage KYC & Whitelist
Available token amount: .... --> Balance: ....
Phase cap amount --> Phase Cap

![telegram-cloud-photo-size-5-6228649091664033254-y](https://github.com/InkWhale-net/frontend/assets/107900832/2d948ef6-79ca-4a90-8b97-75ddb7643cdf)

**Comment by langdon0003** [comment]
Updated
@phoebehoang85

**Comment by phoebehoang85** [comment]
Sửa text:
KYC means Know Your Customer (or Client). KYC or KYC check is the mandatory process of identifying and verifying the customer or client's identity when buying tokens.

![image](https://github.com/InkWhale-net/frontend/assets/107900832/8daffc78-29c3-4eb9-960f-8483f3dc105c)
