### ISSUE TITLE
Update phase: Báo lỗi khi Release rate = 0%

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#316]
Update phase: Báo lỗi khi Release rate = 0%

Chỉnh lại để release rate được = 0%

![image](https://github.com/InkWhale-net/frontend/assets/107900832/b93a8902-b3cf-4125-bab5-3cb10c524e7b)

**Comment by phoebehoang85** [comment]
@langdon0003 

Check Phase cap luôn, không chờ kí rồi mới báo lỗi


![image](https://github.com/InkWhale-net/frontend/assets/107900832/a28a9de3-8fee-466f-b0a0-1daae221579b)

**Comment by langdon0003** [comment]
Update Allowed Update phase: Release rate = 0%
@phoebehoang85
