### ISSUE TITLE
KYC:  khi có nhiều hơn 1 phase thì chú thích whitelist ở các phase không chính xác

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#317]
khi có nhiều hơn 1 phase thì chú thích whitelist ở các phase không chính xác

Add whitelist cho address này ở phase 2, nhưng "You are in the whitelist" đang hiển thị luôn phase 1 (mặc dù không mua được)

![image](https://github.com/InkWhale-net/frontend/assets/107900832/d6dce665-b5b4-4fc9-baaf-926b5de5eaf6)

Ra ngoài mua, thì thấy hiển thị "You are in the whitelist" ở phase bootcamp 1

![image](https://github.com/InkWhale-net/frontend/assets/107900832/af5e22fe-0c2d-458c-a575-4c39e96b419a)

Ngoài ra các phase bootcamp 1 không có chú thích "Whitelist Only" còn boothcamp 2 lại có, bản chất 2 phase là như nhau , có thể chuyển chú thích tất cả các phase là "KYC required"

![Uploading image.png…]()

**Comment by langdon0003** [comment]
Hiện e test thử thấy đang hiện info ntn @phoebehoang85 

proj address: 5F3z3n89XTnEeLgxKKTq3jpig41nrQVegc3bXBE49ZDXaQyS
![image](https://github.com/InkWhale-net/frontend/assets/35419213/21d2e338-eaf9-4dd1-afa6-16bba9fb646f)


Not in WL
- wallet address: 5H1kx...Mh8n8
- phase added: "Phase Mot"


![image](https://github.com/InkWhale-net/frontend/assets/35419213/7bcacc5f-56f6-47e8-9f41-33b9481e6de9)



In Whitelist
- wallet address: 5HdV9...Zbzn9
- phase added: "Phase Mot"
![image](https://github.com/InkWhale-net/frontend/assets/35419213/f75d22b7-c67f-47de-be77-07aaf7011b18)
