### ISSUE TITLE
STAKE AND UNSTAKE giá trị bằng 0

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#33]
Khi stake 0 token or unstake 0 token, nên hiển thị thông báo lỗi là bạn phải nhập ít nhất >0 token..
![image](https://github.com/InkWhale-net/frontend/assets/55371727/f7930340-bf37-4daa-92c5-c328bde3cb02)

**Comment by phoebehoang85** [comment]
re-test & close case

![Uploading image.png…]()
