### ISSUE TITLE
KYC: Sắp xếp điều chỉnh lại UI group stats info (Public + Whitelist)

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#330]
KYC: Sắp xếp điều chỉnh lại UI group stats info (Public + Whitelist)

![image](https://github.com/InkWhale-net/frontend/assets/107900832/4c95d9bc-d21c-4b57-9dad-79a9242626dc)

**Comment by phoebehoang85** [comment]
Nếu có KYC:
Thêm các thông tin:
           + Time start: ...
           + Time end: ....
           + Available token amount: ... $
           + Phase cap amount: .... $
           + Whitelist added: ... addresses ... $
           + Whitelist claimed: ..... addresses ... $

Nếu không KYC:
Thêm các thông tin:

**Comment by langdon0003** [comment]
![image](https://github.com/InkWhale-net/frontend/assets/35419213/2c69fc60-b9b1-4bc2-b93a-37acf1406d52)
