### ISSUE TITLE
Launchpad: Chỉnh lại Project detail

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#332]
Launchpad: Chỉnh lại trang Project detail:

(Tab) General Information

Launchpad contract					5HWmi...QxF9i
Description    							text
Token total for sale					100,000 IPPA
Presale Start Time (bỏ Presale)			November 7th 2023, 6:48:02 pm
Presale End Time  (bỏ Presale)			November 8th 2023, 6:55:37 pm
Unsold Token	(thêm)					(cho chọn các options: Burn / Keep / Airdrop / Others (yêu cầu viết)
(Thêm) (cho chọn options: To be listed on / Already listed on)	(cho chọn các options: Common / Panorama / Andromeda / Others (yêu cầu viết text))					
(còn 1 số các thông tin khác: Estimated Initial Market Cap / Soft Cap / Hard Cap / Liquidity percent / Liquidity / Liquidity lock up time không biết có cần cho vào không?)

Tokenomic 

Pie chart

Roadmaps

Milestone 1
Name								text
Description							text

Milestone 2
Name								text
Description							text

Team member

Avatar			Name
				Role
				Social link:

Avatar			Name
				Role
				Social link:

(Tab) Phase (đổi thành Sale Phases)

Phase name 1

Not Active

Start Date & Time			November 7th 2023, 6:48:02 pm
End Date & Time				November 7th 2023, 11:48:00 pm

Vesting Plan

Immediate Release Rate 				10%
Vesting Duration						1 day(s)
Vesting Release Period					0.0104 day(s)
Phase Cap Amount					20000 $IPPA

Phase status							00:00:00:00

(Tab) Token
Name						IPPA (bỏ logo)
Symbol						IPPA (bỏ logo)
Logo (thêm)						(hình)
Decimal						12
Address						5CWRo...4T5kh
Total supply					1,000,000 IPPA

(Tab) Balance

Phase name
Total purchased				0 IPPA
Claimed						0 IPPA

Claim button

Phase name
Total purchased				0 IPPA
Claimed						0 IPPA

Claim button
…

**Comment by langdon0003** [comment]
updated
@phoebehoang85
