### ISSUE TITLE
Launchpad Detail: Thêm thông tin ở phần Owner Zone

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#333]
Thêm 1 số thông tin ở phần owner zone trên trang Launchpad Detail:

- Launchpad babance
           + Total token for sale: ...
           + Total sold: ....
                       Phase 1: ....
                       Phase 2: ...
                        ....
           + Withdrawn: ...
           + Burned: ...
           + Whitelist added: ... addresses
          + Whitelist claimed: ..... addresses

![image](https://github.com/InkWhale-net/frontend/assets/107900832/17563b25-b6af-42c3-b649-499ea0b89e3c)

**Comment by langdon0003** [comment]
![image](https://github.com/InkWhale-net/frontend/assets/35419213/c1dba155-8259-469d-9ba5-a271472d990d)
@phoebehoang85
