### ISSUE TITLE
UI, UX

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#34]
Lỗi hiển thị, Số lượng NFT thiếu S: 30 NFTs, chứ k phải 30 NFT
![image](https://github.com/InkWhale-net/frontend/assets/55371727/f6c69ad2-8ab3-437b-a3d5-b2a905a0b1a8)

**Comment by phoebehoang85** [comment]
close case

![image](https://github.com/InkWhale-net/frontend/assets/107900832/7f067bab-38b6-4b97-aa87-80f7a230e244)
