### ISSUE TITLE
Whitelist: không add được khi phase đang chạy

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#343]
Whitelist: không add được khi phase đang chạy (single add)

Với whitelíst manager, được add thêm / edit khi:
- phase chưa bắt đầu hoặc đã bắt đầu nhưng chưa kết thúc
- Thêm token, bớt token, những token đã mint rồi thì không xoá hoặc giảm được nhưng thêm được (ở đây đang không cho edit)

Add được bulk, sau khi add xong không tự refresh.

Sửa lại format add bulk bỏ dấu cách giữa các trường để dễ sử dụng khi copy csv file

![image](https://github.com/InkWhale-net/frontend/assets/107900832/c4c114cf-2c93-4125-a607-8957b1f67318)

![image](https://github.com/InkWhale-net/frontend/assets/107900832/750c05bd-0b5c-4ba8-8c9b-2421a981538b)

![image](https://github.com/InkWhale-net/frontend/assets/107900832/16caa987-8258-4498-a953-1a5650ecd73c)

**Comment by langdon0003** [comment]
Update @phoebehoang85
