### ISSUE TITLE
[Pretest] Không remove reward được do làm tròn

### ISSUE THREAD

**Issue by vup2p** [InkWhale-net/frontend#346]
![image](https://github.com/InkWhale-net/frontend/assets/102939807/79ecbfdc-8e36-4be3-9d83-4015f77ca726)

**Comment by vup2p** [comment]
vẫn bị 
![image](https://github.com/InkWhale-net/frontend/assets/102939807/7e03129c-980a-471a-8cd4-5d90cdc072db)

**Comment by langdon0003** [comment]
updated on https://testnet.inkwhale.net
@phoebehoang85 @Shinie16
