### ISSUE TITLE
[Pretest] Sai token

### ISSUE THREAD

**Issue by vup2p** [InkWhale-net/frontend#347]
![image](https://github.com/InkWhale-net/frontend/assets/102939807/4ab5aa8f-244e-48cc-9536-da6d70aab54a)

**Comment by vup2p** [comment]
vẫn hiển thị ink cũ

**Comment by langdon0003** [comment]
![image](https://github.com/InkWhale-net/frontend/assets/35419213/ae335f91-8648-4927-8efb-75ffbdfa634c)

![image](https://github.com/InkWhale-net/frontend/assets/35419213/8e135ce5-ba63-47ae-8b12-f3e9f326ae1f)

![image](https://github.com/InkWhale-net/frontend/assets/35419213/7d64b5c2-d42a-4acb-89b0-00bdc7602089)

![image](https://github.com/InkWhale-net/frontend/assets/35419213/c4297f95-c06c-4be4-af67-c3bac81723ed)

a check thấy hiện đúng, ảnh của e là giống case 3 dùng tạo INW cũ nên hiện theo ink cũ @vup2p

**Comment by langdon0003** [comment]
Pls check and confirm on https://testnet.inkwhale.net/
@phoebehoang85 @Shinie16
