### ISSUE TITLE
[Pretest] Không tạo được farming pool

### ISSUE THREAD

**Issue by vup2p** [InkWhale-net/frontend#350]
![image](https://github.com/InkWhale-net/frontend/assets/102939807/8feae5e7-eb31-4dd4-95dd-f25b9d7d2a86)

![image](https://github.com/InkWhale-net/frontend/assets/102939807/ad5ff8f0-02c9-4d4a-b417-6ae6e639ec53)

**Comment by langdon0003** [comment]
@vup2p thử tạo vài cái bên pretest xem còn bị ko nhé
