### ISSUE TITLE
Whitelist mint lỗi (KYC)

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#357]
Whitelist mint lỗi (KYC)

Add KYC vào phase 3 nhưng chưa kịp mint thì hết giờ. Sau đó project hết phase, tạo thêm phase 4, add tiếp KYC này vào phase 4, mint lỗi, đã refresh và thử lại nhiều lần

![telegram-cloud-photo-size-5-6269392689032182304-y](https://github.com/InkWhale-net/frontend/assets/107900832/9765a753-c4c8-4847-9fdc-93829d9d0af7)

**Comment by langdon0003** [comment]
Updated @phoebehoang85
