### ISSUE TITLE
Token: transfer token nhưng balance ở ô bên trái không nhảy

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#36]
Token: transfer token nhưng balance ở ô bên trái không nhảy, phải refresh mới nhảy.
Nên nếu check balance của tk đó thì balance ra khác mà kết quả check balance ra khác nhau

![image](https://github.com/InkWhale-net/frontend/assets/107900832/4111b335-7267-4991-bb69-335f3bc904fb)

**Comment by langdon0003** [comment]
Fix at commit [dc65e318b798368921c3f4015f707fd4eb08b4ec](https://github.com/InkWhale-net/frontend/commit/dc65e318b798368921c3f4015f707fd4eb08b4ec) for both Transfer and Burn token.

**Comment by phoebehoang85** [comment]
re-test & close case
