### ISSUE TITLE
5test: Lên trang acquire INW

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#398]
5test: Lên trang acquire INW để user mua được mà test. Bỏ vesting đi chỉ để trang acquire INW thôi
Giá 0.035 5ire

**Comment by langdon0003** [comment]
Done please check @phoebehoang85

**Comment by phoebehoang85** [comment]
Đẩy lại trên trang Acquire INW cả phần summaries bên trái như trang a0 nữa nhé em. Trên thanh toolbar trên cùng đặt nút Acquire INW nữa @langdon0003 

![image](https://github.com/InkWhale-net/frontend/assets/107900832/39ddd7b8-8b21-4b12-b04c-1db20d303ef3)

**Comment by langdon0003** [comment]
Temp add `In Circulation` and `Total Supply` @phoebehoang85
