### ISSUE TITLE
5test: đưa contract INW token lên đầu trang Token interaction

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#400]
5test: đưa contract INW token lên đầu trang Token interaction

![image](https://github.com/InkWhale-net/frontend/assets/107900832/769cfbcd-306c-4361-80f0-18e8b2ae1e96)

**Comment by langdon0003** [comment]
need update env of FE 5test following field @vup2p @huyp26102000  `REACT_APP_INW_TOKEN_ADDRESS=5FNhUSS5qvxDnQm61qtmufoozyhuc15ae5He791ydSi9sJcS`
