### ISSUE TITLE
[5iretest] - Create token

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#401]
1. Có thể tạo token thành công với ký tự đặc biệt, text có dấu (tiếng Việt), ví dụ: #,@, ứd,... --> Đối với token tạo bằng tên tiếng Việt, khi tạo thành công nhưng kết quả không hiển thị tên token, balance, symbol, Decimal,... (xem hình đính kèm bên dưới)
2. Sau khi tạo thành công token không hiển thị trên tab "Recent Tokens"
3. Không hiển thị icon logo của dự án ở tab "Recent Tokens"

![image](https://github.com/InkWhale-net/frontend/assets/55371727/f0a4f229-04de-49f3-819d-3d0af0acda11)
![image](https://github.com/InkWhale-net/frontend/assets/55371727/e0bb132f-4fba-4e7d-93e5-66da281ed959)
4. Không thể xóa số đầu tiên khi nhập vào field "total supply": Ví dụ khi bạn viết số 1 vào đầu tiên bạn không thể xóa số đó đi, nếu bạn nhập số 123, bạn chỉ có thể xóa số 2,3 nhưng số 1 thì lại không
![image](https://github.com/InkWhale-net/frontend/assets/55371727/dafaf0d4-e20c-49f2-ab72-b97ad041a7de)

**Comment by langdon0003** [comment]
1,2,3 updated @Shinie16

**Comment by Shinie16** [comment]
E vẫn tạo được token với chữ cái đặc biệt í anh @langdon0003 
![image](https://github.com/InkWhale-net/frontend/assets/55371727/620ec80a-b190-4567-9dc2-4e7433088936)

**Comment by langdon0003** [comment]
Updated point 1 & 4 on https://testnet.inkwhale.net

Please check @Shinie16

**Comment by langdon0003** [comment]
Updated point 1 & 4 on on 5ire as well

Please check @Shinie16

**Comment by Shinie16** [comment]
E mới tạo token trên 5ire, nó không hiển thị ảnh logo trên tab "recent token" và "My token" as well @langdon0003 
![image](https://github.com/InkWhale-net/frontend/assets/55371727/338774b8-285a-4f31-bbad-df96853de336)
![image](https://github.com/InkWhale-net/frontend/assets/55371727/7ce88c1f-d91e-40c1-8b42-14526d775b64)

**Comment by Shinie16** [comment]
1, 4 ok a nhé! done! @langdon0003

**Comment by hiro2kqt** [comment]
> E mới tạo token trên 5ire, nó không hiển thị ảnh logo trên tab "recent token" và "My token" as well @langdon0003 ![image](https://private-user-images.githubusercontent.com/55371727/298802391-338774b8-285a-4f31-bbad-df96853de336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTk5NjIsIm5iZiI6MTcwNjA1OTY2MiwicGF0aCI6Ii81NTM3MTcyNy8yOTg4MDIzOTEtMzM4Nzc0YjgtMjg1YS00ZjMxLWJiYWQtZGY5Njg1M2RlMzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxMjc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZTg3NDBmMTJhZTFkZmFhN2E4ZjQ2MDVhNWZlNTZkZDVmNDk0ZmYwZjA3NDg3MWRiZDI3ZjlkMTA5NDJiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2GSC6eJL6A0P1kBKUWkXO4LJTwWiQlx3wv7384Xh56c) ![image](https://private-user-images.githubusercontent.com/55371727/298802471-7ce88c1f-d91e-40c1-8b42-14526d775b64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNTk5NjIsIm5iZiI6MTcwNjA1OTY2MiwicGF0aCI6Ii81NTM3MTcyNy8yOTg4MDI0NzEtN2NlODhjMWYtZDkxZS00MGMxLThiNDItMTQ1MjZkNzc1YjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxMjc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZGI4YTQ5ZTg1ZTM4OGY1NDc0NzJjMzhjNGNiNmZhMGI1ZGY4Mjc3NGYyNmYzNTNmNzE5OTA0YTA4OTllODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E-ZvJiyBsohKoodlQc-OmV2eMTaXviPoLUjfrtkdsdw)

đã fix nhờ chị check
