### ISSUE TITLE
Balance Tzero hiển thị sai

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#404]
Check lại trường hợp này k biết tại sao Tzero hiển thị sai số

Trong https://test.azero.dev/#/accounts ví Albert 127,610.1761 mà trên platform của mình 108,038.6641 AZERO

![image](https://github.com/InkWhale-net/frontend/assets/107900832/5a7857d6-69eb-4e48-a67e-885f352fa8cf)

![image](https://github.com/InkWhale-net/frontend/assets/107900832/bbd460c6-0834-46f9-8f5f-02c11bf5cf12)

**Comment by langdon0003** [comment]
Wallet balace have a lock portion -> can not use
@phoebehoang85 

![image](https://github.com/InkWhale-net/frontend/assets/35419213/8e40ebe4-a666-420b-8ff2-a5504d28a25b)

**Comment by langdon0003** [comment]
won't fix it. close please @phoebehoang85
