### ISSUE TITLE
Azero Staking Testnet: mới stake lần đầu chưa claim nhưng đã có last claimed time

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#405]
Azero Staking Testnet: mới stake lần đầu chưa claim nhưng đã có last claimed time (đang hiển thị là thời gian stake hay sao ấy)

![image](https://github.com/InkWhale-net/frontend/assets/107900832/50675a8e-3119-4421-8ba2-2d1e435ec46b)

![image](https://github.com/InkWhale-net/frontend/assets/107900832/0ce762fd-3b48-47f7-8ca2-9e85a919bf47)

**Comment by langdon0003** [comment]
Updated

![image](https://github.com/InkWhale-net/frontend/assets/35419213/88a7a0d3-f9f7-4b58-bd4f-9f0a7c915f47)

**Comment by langdon0003** [comment]
Updated one https://testnet.inkwhale.net/ 
@phoebehoang85 @Shinie16
