### ISSUE TITLE
5test: bảng thông tin trong interaction sai, nhầm INW & IWN

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#408]
5test: bảng thông tin trong interaction sai
Load INW nhưng vừa hiện INW vừa hiện IWN
--> cần hiện Azero + INW
Transfer INW nhưng thành transfer IWN

![image](https://github.com/InkWhale-net/frontend/assets/107900832/8a01d76b-c818-4e90-a53d-acce0fe99b95)

**Comment by hiro2kqt** [comment]
Sai name & symbol lúc deploy, sau này sẽ deploy lại sau
