### ISSUE TITLE
5test: tạo pool lỗi

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#409]
5test: tạo pool lỗi
toast như dưới đây
lần thứ 2 tạo pool thì thành công, size pool nhỏ hơn thì ok, sau đó quay lại tạo lại size pool này vẫn lỗi như vậy

![image](https://github.com/InkWhale-net/frontend/assets/107900832/d4158a76-c4d3-4c94-95d2-7f507c0e2ad7)

**Comment by hiro2kqt** [comment]
chị cho tham số cụ thể ạ  @phoebehoang85

**Comment by hiro2kqt** [comment]
@phoebehoang85 đã fix nhờ chị check
