### ISSUE TITLE
[Testnet] - Azero staking

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#411]
1. Chỉnh text: **50,000 AZERO** thay vì 50000 AZERO vì hơi khó nhìn
![image](https://github.com/InkWhale-net/frontend/assets/55371727/e81b635b-9f46-4fbd-b6d2-49a160e0e7e6)

2. Chỉnh text:
- Claim Rewards: **Claimed Rewards**
- Stake: **Staked**
- Request Unstake: **Requested Unstake**
![image](https://github.com/InkWhale-net/frontend/assets/55371727/abe7387b-8e7b-4440-8899-8bbf15e702e3)

3. Chỉnh text:
- Remain total staking: **Remaining total staking**
![image](https://github.com/InkWhale-net/frontend/assets/55371727/c2e9ff92-982e-4dc2-b3be-4bc6e8f12aaa)

4. Chỉnh text:
- My Unstake History: **My Unstaking History**
![image](https://github.com/InkWhale-net/frontend/assets/55371727/cc1b35c8-9655-44d0-be31-7e37bf1b9200)

5. Chỉnh text: 
Note: 5 INW will be charged and burned for each claim!--> **Note: A fee of 5 INW will be charged and burned for each claim.**
![image](https://github.com/InkWhale-net/frontend/assets/55371727/bf03f1eb-ad85-4171-bc47-7d12ad0c0c08)

**Comment by langdon0003** [comment]
Updated @Shinie16

**Comment by Shinie16** [comment]
Trong tab "**My Transaction**" chưa edit a nha @langdon0003 
![image](https://github.com/InkWhale-net/frontend/assets/55371727/62014263-24a2-4a68-9e2a-19bcc9dad984)
![image](https://github.com/InkWhale-net/frontend/assets/55371727/c0772921-df89-4dc6-8d96-c49e732c911b)

**Comment by langdon0003** [comment]
updated @Shinie16
