### ISSUE TITLE
[5test + testnet + pretest] Không add được APR / multiplier là số thập phân

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#414]
[5test + testnet + pretest] Không add được APR / multiplier là số thập phân
Bản Mainnet thì add được, các bản còn lại đều không add được số thập phân

![image](https://github.com/InkWhale-net/frontend/assets/107900832/47ab33d1-82ba-4c79-83a8-db0f3aeb42f3)

**Comment by langdon0003** [comment]
Updated @phoebehoang85
