### ISSUE TITLE
[Testnet] Token Interaction nếu load đồng INW thì bị lặp hiển thị 

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#415]
[Testnet] Token Interaction nếu load đồng INW thì bị lặp hiển thị: có 2 INW balance ở bên trái

![image](https://github.com/InkWhale-net/frontend/assets/107900832/4dc21210-e736-4f30-a308-4256c29bde6c)

**Comment by langdon0003** [comment]
updated INW&INW2 on testnet
updated INW on 5iretest
@phoebehoang85
