### ISSUE TITLE
[testnet + pretest] insert đồng INW v2 lên các bản

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#416]
[testnet + pretest] insert đồng INW v2 lên, trong phần lựa chọn token ở Interaction / Transactions / Pools / Farms... default đứng thứ 1 là INW, đứng thứ 2 là INW V2

![image](https://github.com/InkWhale-net/frontend/assets/107900832/4376f67e-fc90-4393-9749-3652981a2410)

**Comment by langdon0003** [comment]
updated @phoebehoang85 
![image](https://github.com/InkWhale-net/frontend/assets/35419213/d07073c6-7722-4a4f-93c4-b5a58f4cda4e)
