### ISSUE TITLE
[Testnet] - Azero Staking

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#420]
Đã giải thích với a Long
![image](https://github.com/InkWhale-net/frontend/assets/55371727/037a68e1-f2c7-4099-95ac-63c9ee3bd8be)

**Comment by langdon0003** [comment]
hold back to double check after issue `[Testnet] - Không stake AZERO với max staking được, thông báo lỗi #421` ís fixed

**Comment by langdon0003** [comment]
updated đã stake được. double check lại nhe @Shinie16
