### ISSUE TITLE
[5iretest] - Acquire INW token

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#423]
1. Nhập số lượng token cần mua lớn hơn INW Available to acquire, nhưng vẫn cần approve ví. Cần chỉnh lại thông báo lỗi luôn khi click "Buy INW" button
![image](https://github.com/InkWhale-net/frontend/assets/55371727/333b68e3-e098-44dc-bb9b-4e01952cea19)
2. Không thể nhập số token là số thập phân để mua token INW
3. Tương tự nhập số lượng token cần mua lớn hơn số dư, cần thông báo lỗi chứ không phải approve ví xong mới thông báo lỗi

**Comment by langdon0003** [comment]
issue `2. Không thể nhập số token là số thập phân để mua token INW` updated at commit [70aeb54](https://github.com/InkWhale-net/frontend/commit/70aeb5492aba47c4598ec377099addb4d3663f3c)

**Comment by langdon0003** [comment]
Updated @Shinie16
