### ISSUE TITLE
[5iretest] - Lỗi khi mua token dưới 1 INW

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#426]
1. Nhập token dưới 1INW thì vẫn thực hiện thao tác approve ví, nhưng sau đó báo lỗi
https://www.loom.com/share/f3eed7bdece740218df43e1981643fe7

2. Khi chưa nhập dữ liệu, tốt nhất button "Buy INW" nên disable, hiện tại vẫn click để approve ví được, nhưng sau đó báo lỗi
![image](https://github.com/InkWhale-net/frontend/assets/55371727/b8666781-4224-4149-a016-99b70fc0dfef)

**Comment by langdon0003** [comment]
Updated @Shinie16
