### ISSUE TITLE
[5iretest] - Thông báo lỗi sai text 

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#428]
Step 1: Nhập số lượng token cần burn lớn hơn số lượng token đang sở hữu
Step 2: Click burn
Step 3: Hiển thị thông báo lỗi
Chỉnh You don't have enough Shinie tokens to transfer! --> **You don't have enough Shinie tokens to burn!**
![image](https://github.com/InkWhale-net/frontend/assets/55371727/618b2d0b-1690-420d-9a9f-877c0b6e3aa1)

**Comment by langdon0003** [comment]
Updated on testnet & 5iretest @Shinie16 
![image](https://github.com/InkWhale-net/frontend/assets/35419213/9c0317da-e1fa-43da-91ee-b7223be47b9b)
