### ISSUE TITLE
[testnet + 5ire] Sau khi tạo pool xong thành công thì trả các trường về blank

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#430]
[testnet + 5ire] Sau khi tạo pool xong thành công thì trả các trường về blank
Hiện tại tạo thành công xong các trường vẫn giữ nguyên như các thông số đã điền trước

![image](https://github.com/InkWhale-net/frontend/assets/107900832/37f2077b-35b3-4ea9-b258-41edabbc4e2b)

**Comment by langdon0003** [comment]
TODOs:

- [x] Reset `SelectSearch` component

**Comment by langdon0003** [comment]
updated @phoebehoang85 @Shinie16
