### ISSUE TITLE
[5ire] Một số trang vẫn đang để Azero --> đổi sang 5ire

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#432]
[5ire] Một số trang vẫn đang để Azero --> đổi sang 5ire

Create Token
![image](https://github.com/InkWhale-net/frontend/assets/107900832/e5d77009-b886-46f7-919f-2afc93f9ab2d)

Create NFT Staking Pool
![image](https://github.com/InkWhale-net/frontend/assets/107900832/cfd24f86-eacf-4290-8015-59ebec92afa8)

xem còn trang nào nữa k cố gắng replace hết azero thành 5ire

**Comment by hiro2kqt** [comment]
@phoebehoang85 nhờ chị check
