### ISSUE TITLE
[Azero staking] - Hiển thị sai thời gian khi staking

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#435]
Khi stake thêm lượng AZERO, hệ thống sẽ tự động reset và cập nhật thời gian latest claim reward
![image](https://github.com/InkWhale-net/frontend/assets/55371727/dfc0836c-9aa2-42a6-ac59-6f12d2af4ac2)

**Comment by Shinie16** [comment]
@langdon0003 em unstake nó thong báo lỗi nhưng vẫn thành công! Chỗ ready for unstaking
![image](https://github.com/InkWhale-net/frontend/assets/55371727/3c2e5ebd-a6e7-488f-a579-e11c877604a6)

**Comment by langdon0003** [comment]
> Khi stake thêm lượng AZERO, hệ thống sẽ tự động reset và cập nhật thời gian latest claim reward ![image](https://private-user-images.githubusercontent.com/55371727/300680359-dfc0836c-9aa2-42a6-ac59-6f12d2af4ac2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjkxNjIsIm5iZiI6MTcwNjY2ODg2MiwicGF0aCI6Ii81NTM3MTcyNy8zMDA2ODAzNTktZGZjMDgzNmMtOWFhMi00MmE2LWFjNTktNmYxMmQyYWY0YWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAyNDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ODA2NmRkZDc1ZTlkNjllMDRmYmU2NDE0NmJkMmU2YmQxN2U5MWMzNzFiODFhMzYxM2NiMjdkZThlYzFkY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TIFQd_N8pTiaKR2YdcVS_nu8MbNvD2UoS49UkJfNeuY)

time này chạy ok @Shinie16

**Comment by langdon0003** [comment]
> @langdon0003 em unstake nó thong báo lỗi nhưng vẫn thành công! Chỗ ready for unstaking ![image](https://private-user-images.githubusercontent.com/55371727/300752065-3c2e5ebd-a6e7-488f-a579-e11c877604a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjkxNjIsIm5iZiI6MTcwNjY2ODg2MiwicGF0aCI6Ii81NTM3MTcyNy8zMDA3NTIwNjUtM2MyZTVlYmQtYTZlNy00ODhmLWE1NzktZTExYzg3NzYwNGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAyNDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZmYwZmM4OWFjZmU0MDk0MmZjNjE5MDEzNTBlNTExYzY1MDM3Y2EyODIzZTIxY2NiMGQ2Y2UwMTlkMjEzODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j6ZO0pctAfJLpnWOnzqrvmzrNT8q6QA9dcqFApoUCPs)

e thử thì thaassy vẫn ok. lần sau ngay khi bị lỗi `ExtrinsicFailed` kiểu tựa ntn e mở console lên chụp giúp a phần liên quan này để thêm info nhé
@Shinie16 
![image](https://github.com/InkWhale-net/frontend/assets/35419213/4073a110-264e-4690-a81a-7829f0a03847)

**Comment by langdon0003** [comment]
please check @Shinie16
