### ISSUE TITLE
[Azero staking] stake các số thập phân history hiển thị kết quả làm tròn 

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#436]
E stake 1.5 A0 và 2,09 A0 nhưng "Transaction history" "My Transaction" chỉ hiển thị 1 và 2
![image](https://github.com/InkWhale-net/frontend/assets/55371727/1dc59a38-2975-466e-a990-69c91bcb1c58)

**Comment by Shinie16** [comment]
![image](https://github.com/InkWhale-net/frontend/assets/55371727/99fad9cc-68ff-42f0-883b-e8e442982058)

**Comment by Shinie16** [comment]
E stake số thập phân nhưng total my stake "My Staked" nó hiển thị số làm tròn luôn, không hiển thị số lẻ thập phân phía sau!!!! 
![image](https://github.com/InkWhale-net/frontend/assets/55371727/476b4836-909d-4b45-83bc-44aa93ace895)

**Comment by langdon0003** [comment]
updated @Shinie16
