### ISSUE TITLE
[Azero staking] - lỗi hiển thị UI button "MAX"

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#437]
Ở tab "stake" kéo xuống phía dưới "My Unstaking History" sẽ thấy bị lỗi hiển thị button max
![image](https://github.com/InkWhale-net/frontend/assets/55371727/1cf6fb95-059a-42f3-81bc-1bf2fb384e07)

**Comment by langdon0003** [comment]
updated @Shinie16
