### ISSUE TITLE
[LAUNCHPAD] - lỗi khi tạo LaunchPad

### ISSUE THREAD

**Issue by Shinie16** [InkWhale-net/frontend#448]
Tạo launchpad without KYC
Chỉ approved ví ở 2 bước và dừng lại ở bước thứ 3 @langdon0003 
![image](https://github.com/InkWhale-net/frontend/assets/55371727/3bbadda6-3086-4783-ab3f-79f2aa8386b3)

**Comment by phoebehoang85** [comment]
Chị tạo thử thấy báo về Vesting period nhưng ở phase 1 không thấy. báo lỗi
Lúc đầu đặt vesting period là 0.0124 thì không cho tạo, khi sửa thành 1 thì ok
Ở phase 2 báo lỗi như này, sửa tất cả thành 1 thì tạo được launchpad.
Như vậy, cần tra lại tất cả các lỗi khi tạo project để báo đỏ phía dưới cho người dùng biết lỗi ở đâu để sửa
![image](https://github.com/InkWhale-net/frontend/assets/107900832/12ac1da5-f298-4b33-9970-66f5e5ef3526)

**Comment by langdon0003** [comment]
updated

please check @phoebehoang85 @Shinie16
