### ISSUE TITLE
Launchpad: Tokenomics: xoá số không được

### ISSUE THREAD

**Issue by phoebehoang85** [InkWhale-net/frontend#449]
Launchpad: Tokenomics: xoá số không được
Nếu nhập số vào rồi xoá đi thì chỉ xoá được số sau, số trước không xoá được, chỉ bôi đen rồi thay số mới được thôi

![image](https://github.com/InkWhale-net/frontend/assets/107900832/a0aa1d66-7607-4b97-9110-3aee15fa87b9)

**Comment by langdon0003** [comment]
updated please check @phoebehoang85
