### ISSUE TITLE
Button color is not correct it seems

### ISSUE THREAD

**Issue by mitchdoan** [InkWhale-net/frontend#8]
Khi stake xong thì bắt đầu tính reward luôn rùi, nên button claim này phải hiển thị màu xanh chứ k phải màu trắng 

![image](https://github.com/InkWhale-net/frontend/assets/117429099/69722eb7-9eb8-4122-bd0c-5c2db0474972)

**Comment by phoebehoang85** [comment]
re-test ok. close case

![image](https://github.com/InkWhale-net/frontend/assets/107900832/22e1ce4e-c867-4d72-aa31-4fc496e496e2)
