### ISSUE TITLE
Token Info UI

### ISSUE THREAD

**Issue by nad128668** [InkWhale-net/frontend#86]
![Screenshot 2023-06-08 at 14 12 16](https://github.com/InkWhale-net/frontend/assets/88643486/e75407b9-39c5-4914-b1c9-c2ee310611fd)
Chia làm 2 cột cho đỡ trống bên phải + thêm Token Logo nếu có trong DB của mình, nếu ko có thì ko hiện

**Comment by nad128668** [comment]
chưa hiện ICON

**Comment by nad128668** [comment]
cho Icon hiện cùng dòng với Token Name, đằng trước

**Comment by hiro2kqt** [comment]
@nad128668
